### PR TITLE
Make work on Rocky Linux 9

### PR DESCRIPTION
**Pull request by pwalczysko**
This is passing on https://github.com/pwalczysko/ansible-role-nfs-mount/actions/runs/6559085949

cc @jburel @khaledk2 @sbesson

### CODE REVIEW

**Review by sbesson — COMMENTED** [review]
- the role changes look minimal and sensible
- same comment as other PRs, GitHub Actions need to be re-enabled across all these repositories 
- the requirement of a dedicated `destroy.yml` step is slightly worrying. Are you anticipating this will be needed across all roles ?

**Comment by pwalczysko** [comment]
> * the requirement of a dedicated `destroy.yml` step is slightly worrying. Are you anticipating this will be needed across all roles ?

Not sure. This is the first time ever that I saw the test failing on the "destroy" step. The error was inspecific, and the ``destroy.yml`` fixed it...
In a bigger scheme of things, adding such file to all repos is not a big prob, but I have no indication this is necessary as yet, see above.

**Comment by jburel** [comment]
The role depends on nfs-share
and nfs-share depends on nfs-mount
This makes the release difficult.
@sbesson @joshmoore Do you remember the logic?

**Comment by joshmoore** [comment]
I do not. Sounds like something I would have tried hard to avoid.

**Pull request merged**
